networks:
  messaging:
    name: messaging
    driver: bridge
  production:
    external: true
    name: production

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    ports:
      - "5672:5672"
    labels:
      - traefik.enable=true
      - traefik.http.routers.rabbitmq.rule=Host(`messaging.facihub.com.br`)
      - traefik.http.routers.rabbitmq.entrypoints=websecure
      - traefik.http.routers.rabbitmq.service=api@internal
      - traefik.http.routers.rabbitmq.tls=true
      - traefik.http.services.rabbitmq.loadbalancer.server.port=15672
    networks:
      - messaging
      - production
