networks:
  production:
    name: production

services:
  traefik:
    image: traefik:3.6
    container_name: traefik
    restart: unless-stopped
    env_file:
      - ../../../.env
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=production"
      - "--api.dashboard=true"
      - "--api.insecure=true"

      - "--entrypoints.web.address=:80"

      - "--log.level=DEBUG"

    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN}`)
      - traefik.http.routers.traefik.entrypoints=web
      - traefik.http.routers.traefik.service=api@internal
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

    networks:
      - production
